Sitegeist:
  Origami:
    useGlobalBinary: false # use globally installed binaries for all formats instead
    globalBinaryPath: ''
    formats:
      'image/jpeg':
        enabled: true
        useGlobalBinary: false # use globally installed binary for the jpeg library instead
        library: 'jpegtran'
        binaryPath: 'jpegtran-bin/vendor/jpegtran'
        arguments: "${'-copy none -optimize ' + (progressive ? '-progressive ' : '') + '-outfile ' + file + ' ' + file}"
        parameters:
          progressive: true # whether or not to serve progressive jpgs

      'image/png':
        enabled: true
        useGlobalBinary: false # use globally installed binary for the png library instead
        library: 'optipng'
        binaryPath: 'optipng-bin/vendor/optipng'
        arguments: "${'-o' + optimizationLevel + ' -strip all -out ' + file + ' ' + file}"
        parameters:
          optimizationLevel: 2 # optimization level (0-7)

      'image/gif':
        enabled: true
        useGlobalBinary: false # use globally installed binary for the gif library instead
        library: 'gifsicle'
        binaryPath: 'gifsicle/vendor/gifsicle'
        arguments: "${'--batch -O' + optimizationLevel + ' ' + file}"
        parameters:
          optimizationLevel: 2 # optimization level (1-3)

      'image/svg+xml':
        enabled: true
        useGlobalBinary: false # use globally installed binary for the svg library instead
        library: 'svgo'
        binaryPath: 'svgo/bin/svgo'
        arguments: "${(pretty ? '--pretty ' : '') + file}"
        parameters:
          pretty: false # keep the output readable
