Sitegeist:
  Origami:
    formats:
      'image/jpeg':
        enabled: false
        command: "${'jpegtran -copy none -optimize -progressive -outfile ' + file + ' ' + file}"

      'image/png':
        enabled: false
        command: "${'optipng -o 2 -strip all -out ' + file + ' ' + file}"

      'image/gif':
        enabled: false
        command: "${'gifsicle --batch -O 2 ' + file}"

      'image/svg+xml':
        enabled: false
        command: "${'svgo ' + file}"

Flowpack:
  JobQueue:
    Common:
      presets:
        sitegeistOrigami:
          className: Flowpack\JobQueue\Doctrine\Queue\DoctrineQueue
      queues:
        imageOptimization:
          preset: sitegeistOrigami
